In [2]:
import numpy as np

# Vector-vector multiplication

In [3]:
u = np.array([2, 4, 5, 6])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    ans = 0.0
    for i in range(n):
        ans = ans + u[i] * v[i]
    return ans

In [6]:
vector_vector_multiplication(u, v)

14.0

In [7]:
u.dot(v)

14

In [8]:
U = np.array((
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
))
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

# Matrix-vector multiplication

In [9]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    row = U.shape[0]
    col = U.shape[1]
    a = np.zeros(U.shape[0])
    for i in range(row):
        temp = 0.0
        for j in range(col):
            temp = temp + U[i, j] * v[j]
        a[i] = temp

    return a

In [10]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [11]:
U.dot(v)

array([14,  5,  5])

In [12]:
V = np.array(
    [
        [1, 1, 2],
        [0, 0.5, 1],
        [0, 2, 1],
        [2, 1, 0]
    ]
)
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Matrix-matrix multiplication

In [13]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    new_row = U.shape[0]
    new_col = V.shape[1]
    a = np.full((new_row, new_col), 0.0)
    
    for i in range(new_row):
        for j in range(new_col):
            a[i, j] = vector_vector_multiplication(U[i], V[:, j])

    return a 

In [14]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [15]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    new_row = U.shape[0]
    new_col = V.shape[1]
    a = np.full((new_row, new_col), 0.0)
    
    for i in range(new_col):
        a[:, i] = matrix_vector_multiplication(U, V[:, i])

    return a    

In [16]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [17]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity matrix

In [18]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
V = V[[0,1,2]]
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [20]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

# Inverse matrix

In [21]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [24]:
V_inv = np.linalg.inv(V)

In [25]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [26]:
V.dot(V_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
V_inv.dot(V)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])