In [1]:
import numpy as np

# Creating arrays

Fill functions are: zeros, ones, full

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.full(5, 10.)

array([10., 10., 10., 10., 10.])

In [88]:
a = np.array((1., 2, 3, 4, 5))
a

array([1., 2., 3., 4., 5.])

In [49]:
a[0] = 4.4
a[0]

4.4

arange req. param: start, end(excluded)

In [63]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

optional param: multiple 

In [64]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [80]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [72]:
np.linspace(66, 100, 100 - 66 + 1)

array([ 66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

------------

# Multidimensional-array

In [81]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [82]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.full((5, 2, 3), 'minji')

array([[['minji', 'minji', 'minji'],
        ['minji', 'minji', 'minji']],

       [['minji', 'minji', 'minji'],
        ['minji', 'minji', 'minji']],

       [['minji', 'minji', 'minji'],
        ['minji', 'minji', 'minji']],

       [['minji', 'minji', 'minji'],
        ['minji', 'minji', 'minji']],

       [['minji', 'minji', 'minji'],
        ['minji', 'minji', 'minji']]], dtype='<U5')

In [99]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
a[(1, 2)]

6

In [108]:
a[2] = np.zeros(3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [109]:
a[:, 1]

array([2, 5, 0])

In [110]:
a[:, 0] = np.ones(3)
a

array([[1, 2, 3],
       [1, 5, 6],
       [1, 0, 0]])

In [111]:
np.array([
    (1,2,3),
    [4,5,6],
    np.full(3, 'minji'),
    np.zeros(3),
])

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['minji', 'minji', 'minji'],
       ['0.0', '0.0', '0.0']], dtype='<U32')

---

# Randomly generated arrays

rand generates random numbers [0, 1)

In [141]:
1 + np.random.rand(4, 2)

array([[1.12558531, 1.20724288],
       [1.0514672 , 1.44080984],
       [1.02987621, 1.45683322],
       [1.64914405, 1.27848728]])

when a seed it set, the random numbers are not truly random

In [140]:
np.random.seed(3)
100 * np.random.rand(3, 2)

array([[55.07979026, 70.81478226],
       [29.09047389, 51.08276052],
       [89.29469543, 89.62930889]])

In [122]:
np.random.seed(3)
np.random.rand(3, 2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309]])

In [146]:
np.random.randint(5, 10) #[low, high)

8

In [147]:
np.random.randint(5, 10, (3, 2)) #([low, high), dimension)

array([[7, 5],
       [6, 7],
       [5, 8]])

---

# Element wise operations

In [169]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Matrix-element operations are applicable to python lists such as:

Addition

In [170]:
a = a + 1
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Scalar multiplication

In [171]:
a = a * 2
a

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

Operation chaining is available too

In [175]:
a = (a / 2) - 1
a

array([-0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

Matrix-matrix operations applies as well

In [180]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
b = a + 1
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [184]:
b + a

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [189]:
b = np.array([
    [4, 5, 6],
    [7, 8, 9]
])
b

array([[4, 5, 6],
       [7, 8, 9]])

Matrices should have the same dimension, when applying any operations

In [194]:
a + b

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

---

# Comparison operations

In [197]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

Returns a boolean array, if no list name and brackets

In [198]:
a >= 3

array([False, False,  True,  True,  True])

Returns the elements array satisfying the condition, if list name and brackets

In [201]:
a[a >= 3] # elements that satisfy the condition

array([3, 4, 5])

In [205]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a[:, 1]

array([2, 5, 8])

In [214]:
a[:, 1]

array([2, 5, 8])

From column 1 of all rows, return the evens

In [223]:
a[:, 1][a[:, 1] % 2 == 0]

array([2, 8])

Explanation:

In [224]:
a[:, 1]

array([2, 5, 8])

In [225]:
a[:, 1] % 2 == 0

array([ True, False,  True])

[2, 4, 5][True, False, True] displays the indexes with the corresponding true values

An easier way is:

In [228]:
row_1 = a[:, 1]
even = row_1[row_1 % 2 == 0]
even

array([2, 8])

In [239]:
a = np.array((5, 3, 9))
a

array([5, 3, 9])

In [241]:
b = np.array([2, 5, 8])
b

array([2, 5, 8])

In [242]:
a > b

array([ True, False,  True])

In [243]:
a[a > b]

array([5, 9])

---

# Summarizing Operations

max, min, std, mean

In [247]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Get the max of 3rd column

In [248]:
a[:, 2].max()

9